### ISSUE TITLE
ligo python library issue: no __init__.py

### ISSUE THREAD

**Issue by cfpark00** [gw-odw/odw-2018#1]
Hello, I am new to GitHub and I apologize if this is not the usual way to report or post an issue.

I just found out that the ligo package, certainly containing ligo.segments does not have a __init__.py file. This should, in principle not be a problem in python3 or later.

I tried out some simple examples with Python2 and 3.7.0, but i got an error.

I added manually __init__.py with no meaningful thing in it(#hahaha) and the problem was solved.

I think it would be good to add __init__.py to all packages to prevent further issues

**Comment by ahnitz** [comment]
This is an issue with the latest builds of lalsuite on pypi. See also this related error report here. https://github.com/gwastro/pycbc/issues/2250

One solution temporarily is to pin the version to a working one such as,

```
import sys
!{sys.executable} -m pip install lalsuite=='6.48.1.dev20180620' pycbc
```

**Comment by duncanmmacleod** [comment]
This is **not** a bug in `ligo`, `ligo-segments`, or `lalsuite`, but a limitation of in-line installations of packages in jupyter notebooks, namely that you can't install a namspace package and get it to work.

You should be able to work around the issue by installing `ligo-common`, which provides the 'missing' file:

```
import sys
!{sys.executable} -m pip install ligo-common lalsuite pycbc
```

**Comment by cfpark00** [comment]
Thank you very much! I understood the problem!
