### ISSUE TITLE
0 - GWOSC python.ipynb // GWpy example's print(events) results change as time goes on

### ISSUE THREAD

**Issue by elwinmartin** [gw-odw/odw-2018#4]
Hi @duncanmmacleod

I liked your talk at the ODW and was running through the tutorials and found that I get more events when I run things now (which is great since this tells me the underlying method is querying new data).

Minor wording updates might make clear up potential confusion if someone very, very new to this tries to run these examples and sees more events than are listed.

**Comment by elwinmartin** [comment]
Totally fine if this is not an "issue" but I figured it couldn't hurt to bring it up. Thanks again for the tutorial/exercises!

**Comment by jkanner** [comment]
Hi @elwinmartin : Thanks!  Glad you are finding the tutorials helpful.  We are currently working on an update for this year, and I appreciate you noticing this issue.
