### ISSUE TITLE
Difference between data from GWpy 0.12.0 and GWpy 0.14.2

### ISSUE THREAD

**Issue by rusruskov** [gw-odw/odw-2018#5]
I've been going through one of the [tutorials][1] from the workshop. A particular issue I am experiencing involves computing the Q-Transform of the data from the Livingston detector around GW170817. The issue is only present in GWpy 0.14.2. [![enter image description here][3]][3]

The same piece of code when ran on GWpy 0.12.0, which is the current stable version, gives: [![enter image description here][4]][4] 

As should be expected. 

My current guess is that it is something related directly to the data which is fed to the Q-Transform functions. Plotting just 15 seconds of data we can see obvious differences between the two versions of GWpy:

[![enter image description here][5]][5]

Something to notice is that GWpy 0.14.2 doesn't change the data when the tag is changed from 'CLN' to 'C00'.

[![enter image description here][6]][6]

It appears that the two versions are fetching data from different sources. When `TimeSeries.fetch_open_data()` is ran on GWpy 0.12.0, python returns:

    Fetched 1 URLs from https://losc.ligo.org for [1187008852 .. 1187008884)
    Reading data... [Done]

compared to GWpy 0.14.2:

    Fetched 1 URLs from www.gw-osc.org for [1187008852 .. 1187008885))
    Reading data... [Done]

---

**What is going on here?** What is the difference between the two sets of data? Is the *GWpy 0.14.2* L1 Q-Transform as it should be or am I doing something wrong? Any help would be appreciated!

---
Code for producing the graphs:

*Q-Transform*

    from gwpy.timeseries import TimeSeries
    from gwosc.datasets import  event_gps
    import matplotlib.pyplot as plt
    from gwpy.plot import Plot
    
    igps = event_gps('GW170817')
    segment = (igps-30, igps+2)
    
    datah = TimeSeries.fetch_open_data('H1', *segment, tag='CLN', cache=True, verbose=True)
    datal = TimeSeries.fetch_open_data('L1', *segment, tag='CLN', cache=True, verbose=True)
    
    dhq = datah.q_transform(frange=(30,500), qrange=(100,110))
    dlq = datal.q_transform(frange=(30,500), qrange=(100,110))
    
    plot, axes = plt.subplots(nrows=2, figsize=(8,6), sharex=True)
    ax1, ax2 = axes
    ax1.imshow(dhq)
    ax2.imshow(dlq)
    ax1.set_xscale('auto-gps')
    ax1.set_epoch(igps)
    ax1.set_xlabel('')
    ax2.set_xlabel('Time [seconds] from GW170817 merger')
    ax1.set_ylabel('Frequency [Hz]', fontsize=14)
    ax1.set_yscale('log')
    ax1.set_title('H1 Q-Transform')
    ax2.set_ylabel('Frequency [Hz]', fontsize=14)
    ax2.set_yscale('log')
    ax2.set_title('L1 Q-Transform')
    plot.suptitle('GWpy 0.14.2')

*Raw data plot GWpy 0.12.0*

    from gwpy.timeseries import TimeSeries
    from gwosc.datasets import  event_gps
    import matplotlib.pyplot as plt
    
    igps = event_gps('GW170817')
    segment = (igps-15, igps+2)
    
    datah = TimeSeries.fetch_open_data('H1', *segment, tag='CLN', cache=True, verbose=True)
    datah2 = TimeSeries.fetch_open_data('H1', *segment, tag='C00', cache=True, verbose=True)
    
    plot = plt.figure(figsize=(10,6))
    hax = plot.add_subplot(2,1,1)
    hax.plot(datah)
    
    lax = plot.add_subplot(2,1,2)
    lax.plot(datah2)
    
    for ax in plot.axes:
        ax.set_epoch(igps)
        ax.set_xlim(igps-15,igps+1)
    
    hax.set_ylabel(r" H1 CLN data [dimensionless] ")
    lax.set_ylabel(r" H1 C00 data [dimensionless] ")
    lax.set_xlabel(r" Time [seconds] from GW170817 merger ")
    
    plot.suptitle('GWpy 0.14.2', fontsize=20)

*Raw data plot GWpy 0.14.2*

    from gwpy.timeseries import TimeSeries
    from gwosc.datasets import  event_gps
    import matplotlib.pyplot as plt
    from gwpy.plot import Plot
    
    igps = event_gps('GW170817')
    segment = (igps-15, igps+2)
    
    datah = TimeSeries.fetch_open_data('H1', *segment, tag='CLN', cache=True, verbose=True)
    datah2 = TimeSeries.fetch_open_data('H1', *segment, tag='C00', cache=True, verbose=True)
    
    plot = Plot(datah, datah2, sharex=True, separate=True)
    plot.axes[0].set_ylabel('H1 CLN data')
    plot.axes[1].set_ylabel('H1 C00 data')
    plot.axes[0].set_xlabel('')
    plot.axes[1].set_xlabel('Time [seconds] from GW170817 merger')
    
    axes = plot.axes
    for ax in axes:
        ax.set_epoch(igps)
        ax.set_xlim(igps-15,igps+1)
    
    plot.suptitle('GWpy 0.14.2', fontsize=20)

  [1]: https://github.com/gw-odw/odw-2018/blob/master/gwpy/3%20-%20Q-transforms%20in%20GWpy.ipynb
  [3]: https://i.stack.imgur.com/5HZcX.jpg
  [4]: https://i.stack.imgur.com/WBR6Y.jpg
  [5]: https://i.stack.imgur.com/Tpp6j.jpg
  [6]: https://i.stack.imgur.com/A8aW2.jpg

**Comment by jkanner** [comment]
Thank you for your question!

Yes, there are different versions of the GW170817 data.  L1 data include a large glitch just before the BNS merger, which you see clearly in the first L1 spectrogram.  In some versions of the released data, we have removed this glitch.  You can see a note about this on the GWTC-1 documentation, under "special cases":
https://www.gw-openscience.org/GWTC-1/

I think the change you are noticing in different versions of gwpy is that we are trying a new "catalog" interface on the GWOSC web site.  The catalog interface includes only access to GWTC-1 data at this time, which does indeed include the glitch.  Most likely, the newest version of gwpy is using this catalog interface, and so data retrieved in this way includes the glitch.  

Of course, if you want data with the glitch removed, you can still use gwpy to load the data file.  But, you will need to first download the file you want from the GWOSC web site.  Then, you can use TimeSeries.read() to read data from the file.

Note also that we are working on an update to the data workshop tutorials, which you are welcome to try as well:
https://github.com/gw-odw/odw-2019

Good luck!
 -jonah

**Comment by jkanner** [comment]
See also figures 1 and 2 in the paper about this event:
https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.119.161101

Best,
  jonah
